# Generated by Django 5.2.17 on 2026-08-19 18:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('incident_id', models.CharField(help_text='Unique incident ID', max_length=64, primary_key=True, serialize=False)),
                ('incident_type', models.CharField(help_text='Type of crisis (e.g. Fire, Flood, Medical Emergency)', max_length=100)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('sos', 'SOS')], default='medium', help_text='Urgency level', max_length=20)),
                ('description', models.TextField(help_text='Detailed situational description')),
                ('latitude', models.FloatField(help_text='Incident GPS latitude')),
                ('longitude', models.FloatField(help_text='Incident GPS longitude')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('resolved', 'Resolved')], default='pending', help_text='Current incident status', max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when crisis was logged')),
                ('response_time', models.IntegerField(blank=True, help_text='Response time in minutes', null=True)),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.CharField(help_text='Unique user identifier', max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Full display name', max_length=150)),
                ('role', models.CharField(choices=[('citizen', 'Citizen'), ('volunteer', 'Volunteer'), ('authority', 'Authority')], default='citizen', help_text='User role profile', max_length=30)),
                ('volunteer_type', models.CharField(blank=True, choices=[('Local Resident', 'Local Resident'), ('NGO Member', 'NGO Member'), ('Social Worker', 'Social Worker'), ('Govt. Official', 'Govt. Official')], help_text='Category of responder', max_length=50, null=True)),
                ('organization', models.CharField(blank=True, help_text='Associated NGO or government entity', max_length=200, null=True)),
                ('bio', models.TextField(blank=True, help_text='Responder bio and certified skills', null=True)),
                ('rating', models.FloatField(default=5.0, help_text='Volunteer performance rating (1.0 to 5.0)')),
                ('total_works', models.IntegerField(default=0, help_text='Total completed emergency responses')),
                ('latitude', models.FloatField(default=34.0522, help_text='Current GPS latitude')),
                ('longitude', models.FloatField(default=-118.2437, help_text='Current GPS longitude')),
                ('preferred_language', models.CharField(default='English', help_text='User preferred language', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alert_id', models.CharField(help_text='Unique alert ID', max_length=64, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(default='Nearby Crisis', help_text='Alert category', max_length=100)),
                ('message', models.TextField(help_text='Broadcast notification message')),
                ('radius_km', models.FloatField(default=5.0, help_text='Geo-fence alert radius in kilometers')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('incident', models.ForeignKey(help_text='Triggering incident', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='api.incident')),
            ],
            options={
                'verbose_name': 'Emergency Alert',
                'verbose_name_plural': 'Emergency Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('resource_id', models.CharField(help_text='Unique resource ID', max_length=64, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(choices=[('food', 'Food'), ('water', 'Water'), ('medical', 'Medical'), ('shelter', 'Shelter')], help_text='Supply type', max_length=30)),
                ('quantity', models.IntegerField(default=0, help_text='Available stock quantity')),
                ('latitude', models.FloatField(help_text='Distribution point latitude')),
                ('longitude', models.FloatField(help_text='Distribution point longitude')),
                ('status', models.CharField(choices=[('available', 'Available'), ('low', 'Low Stock'), ('unavailable', 'Unavailable')], default='available', help_text='Inventory availability status', max_length=20)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Last inventory sync timestamp')),
                ('updated_by', models.ForeignKey(help_text='User who updated this stock', on_delete=django.db.models.deletion.CASCADE, related_name='managed_resources', to='api.userprofile')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='incident',
            name='reported_by',
            field=models.ForeignKey(help_text='User who logged the report', on_delete=django.db.models.deletion.CASCADE, related_name='reported_incidents', to='api.userprofile'),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('message_id', models.CharField(help_text='Unique message ID', max_length=64, primary_key=True, serialize=False)),
                ('user_name', models.CharField(help_text='Sender display name', max_length=150)),
                ('role', models.CharField(help_text='Sender role', max_length=30)),
                ('text', models.TextField(help_text='Message text content')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('language', models.CharField(default='English', help_text='Language of message', max_length=30)),
                ('channel_id', models.CharField(default='general', help_text="Channel ID ('general', incident ID, or 'ai-assistant')", max_length=64)),
                ('user', models.ForeignKey(help_text='Sender user', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.userprofile')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerEvaluation',
            fields=[
                ('evaluation_id', models.CharField(help_text='Unique evaluation ID', max_length=64, primary_key=True, serialize=False)),
                ('rating', models.FloatField(help_text='Rating score out of 5.0')),
                ('comment', models.TextField(help_text='Official performance assessment comments')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('linked_work_id', models.CharField(blank=True, help_text='Optional linked incident or resource ID', max_length=64, null=True)),
                ('authority', models.ForeignKey(help_text='Authoritative officer', on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_given', to='api.userprofile')),
                ('volunteer', models.ForeignKey(help_text='Evaluated volunteer', on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_received', to='api.userprofile')),
            ],
            options={
                'verbose_name': 'Volunteer Evaluation',
                'verbose_name_plural': 'Volunteer Evaluations',
                'ordering': ['-timestamp'],
            },
        ),
    ]
